export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_MARKETS_SUCCESS = 'LOAD_MARKETS_SUCCESS';
export const MARKET_SELECTION_CHANGED = 'MARKET_SELECTION_CHANGED';
