export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_MARKETS_SUCCESS = 'LOAD_MARKETS_SUCCESS';
export const ADD_MARKET_SELECTION = 'ADD_MARKET_SELECTION';
export const REMOVE_MARKET_SELECTION = 'REMOVE_MARKET_SELECTION';
